-- Sane defaults
vim.cmd("set mouse=a")
vim.cmd("set laststatus=2")
vim.cmd("set number")
vim.cmd("set tabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set expandtab")
vim.cmd("set autoindent")
vim.cmd("set backspace=indent,eol,start")
vim.cmd("set clipboard^=unnamed,unnamedplus")
vim.cmd("set nowrap")
vim.cmd("nohlsearch")
vim.cmd("set incsearch")
vim.cmd("set colorcolumn=80,120")
vim.cmd("set signcolumn=number")
vim.cmd("set nohlsearch")